// <auto-generated />
using AddContact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddContact.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20231208005718_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AddContact.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Category = 2,
                            Email = "jinny.park@gmail.com",
                            FirstName = "Jinny",
                            LastName = "Park",
                            Phone = 123456789
                        },
                        new
                        {
                            ContactId = 2,
                            Category = 1,
                            Email = "amr.shier@yahoo.com",
                            FirstName = "Amr",
                            LastName = "Shier",
                            Phone = 987654321
                        },
                        new
                        {
                            ContactId = 3,
                            Category = 0,
                            Email = "rawda.email@gmail.com",
                            FirstName = "Rawda",
                            LastName = "Emad",
                            Phone = 547354311
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
